version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-clj-v4
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: 'Test'
          command: |
            lein deps
            lein test
      - run:
          name: 'Lint'
          command: 'lein eastwood "{:exclude-linters [:wrong-pre-post]}"'

workflows:
  version: 2
  commit:
    jobs:
      - build
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
